// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcZFNZGSnCKJZ7vk3wAs495jiIaq3E3Gs',
    appId: '1:1063885275798:web:c6955440837ffc305678b7',
    messagingSenderId: '1063885275798',
    projectId: 'vibeconnect-bac57',
    authDomain: 'vibeconnect-bac57.firebaseapp.com',
    storageBucket: 'vibeconnect-bac57.firebasestorage.app',
    measurementId: 'G-N350XTY8WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7KwhfNBHYyadCMReADbBhD4O9zE-ennY',
    appId: '1:1063885275798:android:206144a4870914775678b7',
    messagingSenderId: '1063885275798',
    projectId: 'vibeconnect-bac57',
    storageBucket: 'vibeconnect-bac57.firebasestorage.app',
  );
}
